"""add_is_deleted_to_heroes

Revision ID: 04d8709b493c
Revises: d25e1e1057a2
Create Date: 2025-08-30 19:28:21.804733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d8709b493c'
down_revision: Union[str, Sequence[str], None] = 'd25e1e1057a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add is_deleted column with default value for existing records
    op.add_column('heroes', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index('ix_heroes_active_created', 'heroes', ['is_deleted', 'created_at'], unique=False)
    op.create_index('ix_heroes_active_only', 'heroes', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_heroes_user_active', 'heroes', ['user_id', 'is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_heroes_user_active', table_name='heroes')
    op.drop_index('ix_heroes_active_only', table_name='heroes', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_heroes_active_created', table_name='heroes')
    op.drop_column('heroes', 'is_deleted')
    # ### end Alembic commands ###
