"""add_series_table_and_series_id_to_stories

Revision ID: 20df1c85b34a
Revises: 1e754f2c9b28
Create Date: 2025-08-31 11:43:49.901598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20df1c85b34a'
down_revision: Union[str, Sequence[str], None] = '1e754f2c9b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_series_active_created', 'series', ['is_deleted', 'created_at'], unique=False)
    op.create_index('ix_series_active_only', 'series', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_series_created_at', 'series', ['created_at'], unique=False)
    op.create_index(op.f('ix_series_id'), 'series', ['id'], unique=False)
    op.create_index('ix_series_user_active', 'series', ['user_id', 'is_deleted'], unique=False)
    op.create_index('ix_series_user_created', 'series', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_series_user_id'), 'series', ['user_id'], unique=False)
    op.drop_column('heroes', 'updated_at')
    op.add_column('stories', sa.Column('series_id', sa.UUID(), nullable=True))
    op.create_index('ix_stories_series_active', 'stories', ['series_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_stories_series_id'), 'stories', ['series_id'], unique=False)
    op.create_foreign_key(None, 'stories', 'series', ['series_id'], ['id'])
    op.drop_column('story_heroes', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_heroes', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.drop_index(op.f('ix_stories_series_id'), table_name='stories')
    op.drop_index('ix_stories_series_active', table_name='stories')
    op.drop_column('stories', 'series_id')
    op.add_column('heroes', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_series_user_id'), table_name='series')
    op.drop_index('ix_series_user_created', table_name='series')
    op.drop_index('ix_series_user_active', table_name='series')
    op.drop_index(op.f('ix_series_id'), table_name='series')
    op.drop_index('ix_series_created_at', table_name='series')
    op.drop_index('ix_series_active_only', table_name='series', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_series_active_created', table_name='series')
    op.drop_table('series')
    # ### end Alembic commands ###
