"""add user onboarding progress table

Revision ID: 3ea74b4c5644
Revises: c55ada0b7e26
Create Date: 2025-09-04 07:40:43.043031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea74b4c5644'
down_revision: Union[str, Sequence[str], None] = 'c55ada0b7e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_onboarding_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_onboarding_completed_at', 'user_onboarding_progress', ['completed_at'], unique=False)
    op.create_index('ix_onboarding_step', 'user_onboarding_progress', ['step_name'], unique=False)
    op.create_index('ix_onboarding_user_completed', 'user_onboarding_progress', ['user_id', 'completed_at'], unique=False)
    op.create_index('ix_onboarding_user_step', 'user_onboarding_progress', ['user_id', 'step_name'], unique=False)
    op.create_index(op.f('ix_user_onboarding_progress_id'), 'user_onboarding_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_onboarding_progress_user_id'), 'user_onboarding_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_onboarding_progress_user_id'), table_name='user_onboarding_progress')
    op.drop_index(op.f('ix_user_onboarding_progress_id'), table_name='user_onboarding_progress')
    op.drop_index('ix_onboarding_user_step', table_name='user_onboarding_progress')
    op.drop_index('ix_onboarding_user_completed', table_name='user_onboarding_progress')
    op.drop_index('ix_onboarding_step', table_name='user_onboarding_progress')
    op.drop_index('ix_onboarding_completed_at', table_name='user_onboarding_progress')
    op.drop_table('user_onboarding_progress')
    # ### end Alembic commands ###
