"""add_hero_ids_array_to_stories

Revision ID: 4e83abfd03dd
Revises: 04d8709b493c
Create Date: 2025-08-30 19:37:46.421501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e83abfd03dd'
down_revision: Union[str, Sequence[str], None] = '04d8709b493c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('hero_ids', sa.ARRAY(sa.UUID()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'hero_ids')
    # ### end Alembic commands ###
