"""init

Revision ID: 883573ac5f55
Revises: 
Create Date: 2025-08-16 11:06:25.860136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '883573ac5f55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('apple_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_active_created', 'users', ['is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_users_apple_id'), 'users', ['apple_id'], unique=True)
    op.create_index('ix_users_apple_id_active', 'users', ['apple_id', 'is_active'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('hero_name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('story_style', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('story_idea', sa.Text(), nullable=False),
    sa.Column('story_length', sa.Integer(), nullable=False),
    sa.Column('child_gender', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stories_active_created', 'stories', ['is_deleted', 'created_at'], unique=False)
    op.create_index('ix_stories_active_only', 'stories', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_stories_age', 'stories', ['age'], unique=False)
    op.create_index('ix_stories_created_at', 'stories', ['created_at'], unique=False)
    op.create_index('ix_stories_gender', 'stories', ['child_gender'], unique=False)
    op.create_index(op.f('ix_stories_id'), 'stories', ['id'], unique=False)
    op.create_index('ix_stories_language', 'stories', ['language'], unique=False)
    op.create_index('ix_stories_length', 'stories', ['story_length'], unique=False)
    op.create_index('ix_stories_style', 'stories', ['story_style'], unique=False)
    op.create_index('ix_stories_user_active', 'stories', ['user_id', 'is_deleted'], unique=False)
    op.create_index('ix_stories_user_created', 'stories', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stories_user_id'), 'stories', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_user_id'), table_name='stories')
    op.drop_index('ix_stories_user_created', table_name='stories')
    op.drop_index('ix_stories_user_active', table_name='stories')
    op.drop_index('ix_stories_style', table_name='stories')
    op.drop_index('ix_stories_length', table_name='stories')
    op.drop_index('ix_stories_language', table_name='stories')
    op.drop_index(op.f('ix_stories_id'), table_name='stories')
    op.drop_index('ix_stories_gender', table_name='stories')
    op.drop_index('ix_stories_created_at', table_name='stories')
    op.drop_index('ix_stories_age', table_name='stories')
    op.drop_index('ix_stories_active_only', table_name='stories', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_stories_active_created', table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_users_apple_id_active', table_name='users')
    op.drop_index(op.f('ix_users_apple_id'), table_name='users')
    op.drop_index('ix_users_active_created', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
