"""Remove is_deleted field from heroes

Revision ID: 89aaf511baaa
Revises: 928a9598cb30
Create Date: 2025-08-29 19:34:58.274615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89aaf511baaa'
down_revision: Union[str, Sequence[str], None] = '928a9598cb30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heroes_active_created'), table_name='heroes')
    op.drop_index(op.f('ix_heroes_active_only'), table_name='heroes', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('ix_heroes_user_active'), table_name='heroes')
    op.drop_column('heroes', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('heroes', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_heroes_user_active'), 'heroes', ['user_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_heroes_active_only'), 'heroes', ['user_id', 'created_at'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('ix_heroes_active_created'), 'heroes', ['is_deleted', 'created_at'], unique=False)
    # ### end Alembic commands ###
