"""heros

Revision ID: 928a9598cb30
Revises: 883573ac5f55
Create Date: 2025-08-29 18:49:28.574747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '928a9598cb30'
down_revision: Union[str, Sequence[str], None] = '883573ac5f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heroes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('appearance', sa.String(), nullable=True),
    sa.Column('personality', sa.String(), nullable=True),
    sa.Column('power', sa.String(), nullable=True),
    sa.Column('avatar_image', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_heroes_active_created', 'heroes', ['is_deleted', 'created_at'], unique=False)
    op.create_index('ix_heroes_active_only', 'heroes', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_heroes_age', 'heroes', ['age'], unique=False)
    op.create_index('ix_heroes_created_at', 'heroes', ['created_at'], unique=False)
    op.create_index('ix_heroes_gender', 'heroes', ['gender'], unique=False)
    op.create_index(op.f('ix_heroes_id'), 'heroes', ['id'], unique=False)
    op.create_index('ix_heroes_user_active', 'heroes', ['user_id', 'is_deleted'], unique=False)
    op.create_index('ix_heroes_user_created', 'heroes', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_heroes_user_id'), 'heroes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heroes_user_id'), table_name='heroes')
    op.drop_index('ix_heroes_user_created', table_name='heroes')
    op.drop_index('ix_heroes_user_active', table_name='heroes')
    op.drop_index(op.f('ix_heroes_id'), table_name='heroes')
    op.drop_index('ix_heroes_gender', table_name='heroes')
    op.drop_index('ix_heroes_created_at', table_name='heroes')
    op.drop_index('ix_heroes_age', table_name='heroes')
    op.drop_index('ix_heroes_active_only', table_name='heroes', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_heroes_active_created', table_name='heroes')
    op.drop_table('heroes')
    # ### end Alembic commands ###
