"""Initial migration

Revision ID: c55ada0b7e26
Revises: 
Create Date: 2025-08-31 16:11:26.487218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55ada0b7e26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('apple_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_active_created', 'users', ['is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_users_apple_id'), 'users', ['apple_id'], unique=True)
    op.create_index('ix_users_apple_id_active', 'users', ['apple_id', 'is_active'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('heroes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('appearance', sa.String(), nullable=True),
    sa.Column('personality', sa.String(), nullable=True),
    sa.Column('power', sa.String(), nullable=True),
    sa.Column('avatar_image', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_heroes_active_created', 'heroes', ['is_deleted', 'created_at'], unique=False)
    op.create_index('ix_heroes_active_only', 'heroes', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_heroes_age', 'heroes', ['age'], unique=False)
    op.create_index('ix_heroes_created_at', 'heroes', ['created_at'], unique=False)
    op.create_index('ix_heroes_gender', 'heroes', ['gender'], unique=False)
    op.create_index(op.f('ix_heroes_id'), 'heroes', ['id'], unique=False)
    op.create_index('ix_heroes_user_active', 'heroes', ['user_id', 'is_deleted'], unique=False)
    op.create_index('ix_heroes_user_created', 'heroes', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_heroes_user_id'), 'heroes', ['user_id'], unique=False)
    op.create_table('series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_series_active_created', 'series', ['is_deleted', 'created_at'], unique=False)
    op.create_index('ix_series_active_only', 'series', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_series_created_at', 'series', ['created_at'], unique=False)
    op.create_index(op.f('ix_series_id'), 'series', ['id'], unique=False)
    op.create_index('ix_series_user_active', 'series', ['user_id', 'is_deleted'], unique=False)
    op.create_index('ix_series_user_created', 'series', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_series_user_id'), 'series', ['user_id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('story_style', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('story_idea', sa.Text(), nullable=False),
    sa.Column('story_length', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stories_active_created', 'stories', ['is_deleted', 'created_at'], unique=False)
    op.create_index('ix_stories_active_only', 'stories', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_stories_created_at', 'stories', ['created_at'], unique=False)
    op.create_index(op.f('ix_stories_id'), 'stories', ['id'], unique=False)
    op.create_index('ix_stories_language', 'stories', ['language'], unique=False)
    op.create_index('ix_stories_length', 'stories', ['story_length'], unique=False)
    op.create_index('ix_stories_series_active', 'stories', ['series_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_stories_series_id'), 'stories', ['series_id'], unique=False)
    op.create_index('ix_stories_style', 'stories', ['story_style'], unique=False)
    op.create_index('ix_stories_user_active', 'stories', ['user_id', 'is_deleted'], unique=False)
    op.create_index('ix_stories_user_created', 'stories', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stories_user_id'), 'stories', ['user_id'], unique=False)
    op.create_table('story_heroes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('hero_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_story_hero_unique', 'story_heroes', ['story_id', 'hero_id'], unique=True)
    op.create_index('ix_story_heroes_hero_id', 'story_heroes', ['hero_id'], unique=False)
    op.create_index(op.f('ix_story_heroes_id'), 'story_heroes', ['id'], unique=False)
    op.create_index('ix_story_heroes_story_id', 'story_heroes', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_story_heroes_story_id', table_name='story_heroes')
    op.drop_index(op.f('ix_story_heroes_id'), table_name='story_heroes')
    op.drop_index('ix_story_heroes_hero_id', table_name='story_heroes')
    op.drop_index('ix_story_hero_unique', table_name='story_heroes')
    op.drop_table('story_heroes')
    op.drop_index(op.f('ix_stories_user_id'), table_name='stories')
    op.drop_index('ix_stories_user_created', table_name='stories')
    op.drop_index('ix_stories_user_active', table_name='stories')
    op.drop_index('ix_stories_style', table_name='stories')
    op.drop_index(op.f('ix_stories_series_id'), table_name='stories')
    op.drop_index('ix_stories_series_active', table_name='stories')
    op.drop_index('ix_stories_length', table_name='stories')
    op.drop_index('ix_stories_language', table_name='stories')
    op.drop_index(op.f('ix_stories_id'), table_name='stories')
    op.drop_index('ix_stories_created_at', table_name='stories')
    op.drop_index('ix_stories_active_only', table_name='stories', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_stories_active_created', table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_series_user_id'), table_name='series')
    op.drop_index('ix_series_user_created', table_name='series')
    op.drop_index('ix_series_user_active', table_name='series')
    op.drop_index(op.f('ix_series_id'), table_name='series')
    op.drop_index('ix_series_created_at', table_name='series')
    op.drop_index('ix_series_active_only', table_name='series', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_series_active_created', table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_heroes_user_id'), table_name='heroes')
    op.drop_index('ix_heroes_user_created', table_name='heroes')
    op.drop_index('ix_heroes_user_active', table_name='heroes')
    op.drop_index(op.f('ix_heroes_id'), table_name='heroes')
    op.drop_index('ix_heroes_gender', table_name='heroes')
    op.drop_index('ix_heroes_created_at', table_name='heroes')
    op.drop_index('ix_heroes_age', table_name='heroes')
    op.drop_index('ix_heroes_active_only', table_name='heroes', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_heroes_active_created', table_name='heroes')
    op.drop_table('heroes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_users_apple_id_active', table_name='users')
    op.drop_index(op.f('ix_users_apple_id'), table_name='users')
    op.drop_index('ix_users_active_created', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
