"""add_story_fields

Revision ID: c9a1edca4653
Revises: b4b48f1eec3b
Create Date: 2025-08-14 15:58:23.765230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a1edca4653'
down_revision: Union[str, Sequence[str], None] = 'b4b48f1eec3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values to handle existing data
    op.add_column('stories', sa.Column('hero_name', sa.String(), nullable=False, server_default='Unknown Hero'))
    op.add_column('stories', sa.Column('age', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('stories', sa.Column('story_style', sa.String(), nullable=False, server_default='Adventure'))
    op.add_column('stories', sa.Column('language', sa.String(), nullable=False, server_default='en'))
    op.add_column('stories', sa.Column('story_idea', sa.Text(), nullable=False, server_default='A magical adventure'))
    
    # Remove server defaults after adding columns
    op.alter_column('stories', 'hero_name', server_default=None)
    op.alter_column('stories', 'age', server_default=None)
    op.alter_column('stories', 'story_style', server_default=None)
    op.alter_column('stories', 'language', server_default=None)
    op.alter_column('stories', 'story_idea', server_default=None)
    
    op.drop_column('stories', 'prompt')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('stories', 'story_idea')
    op.drop_column('stories', 'language')
    op.drop_column('stories', 'story_style')
    op.drop_column('stories', 'age')
    op.drop_column('stories', 'hero_name')
    # ### end Alembic commands ###
