"""remove_hero_fields_from_stories

Revision ID: d25e1e1057a2
Revises: 89aaf511baaa
Create Date: 2025-08-30 19:24:46.556873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd25e1e1057a2'
down_revision: Union[str, Sequence[str], None] = '89aaf511baaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_age'), table_name='stories')
    op.drop_index(op.f('ix_stories_gender'), table_name='stories')
    op.drop_column('stories', 'hero_name')
    op.drop_column('stories', 'age')
    op.drop_column('stories', 'child_gender')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('child_gender', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('stories', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stories', sa.Column('hero_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_stories_gender'), 'stories', ['child_gender'], unique=False)
    op.create_index(op.f('ix_stories_age'), 'stories', ['age'], unique=False)
    # ### end Alembic commands ###
