name: Deploy to Cloud Run

on:
  workflow_dispatch:
    inputs:
      admin_mode:
        description: "Enable admin mode"
        required: true
        type: choice
        default: "false"
        options:
          - "false"
          - "true"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ .secrets.GCLOUD_SA_KEY }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: coffee-point-api
          image: europe-west3-docker.pkg.dev/${{ .secrets.GCLOUD_PROJECT_ID }}/coffee-point-crm/coffee-point-crm:latest
          region: europe-west3
          allow_unauthenticated: true
          add_cloudsql_instances: ${{ .secrets.INSTANCE_CONNECTION_NAME }}
          memory: 1Gi
          env_vars: |
            ADMIN_MODE=${{ github.event.inputs.admin_mode }}
            USE_CLOUD_SQL_PROXY=true
            INSTANCE_CONNECTION_NAME=${{ secrets.INSTANCE_CONNECTION_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASS=${{ secrets.DB_PASS }}
            PRIVATE_KEY_ID=${{ secrets.PRIVATE_KEY_ID }}
            PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}
            JWT_POINT_SECRET_KEY=${{ secrets.JWT_POINT_SECRET_KEY }}
