# API Error Codes Constants

# Authentication Errors
USER_EXISTS = "USER_EXISTS"
USER_NOT_FOUND = "USER_NOT_FOUND"
INVALID_PASSWORD = "INVALID_PASSWORD"
TOKEN_EXPIRED = "TOKEN_EXPIRED"
INVALID_APPLE_CREDENTIALS = "INVALID_APPLE_CREDENTIALS"

# Validation Errors
VALIDATION_ERROR = "VALIDATION_ERROR"

# Authorization Errors
UNAUTHORIZED = "UNAUTHORIZED"
FORBIDDEN = "FORBIDDEN"

# Server Errors
INTERNAL_ERROR = "INTERNAL_ERROR"
SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"

# Resource Errors
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
RESOURCE_CONFLICT = "RESOURCE_CONFLICT"

# Story Errors
STORY_NOT_FOUND = "STORY_NOT_FOUND"
STORY_GENERATION_FAILED = "STORY_GENERATION_FAILED"
